### ISSUE TITLE
Work on event check in

### ISSUE THREAD

**Issue by luisbenan** [SHPEUCF/shpeucfapp#10]
Use/explore https://www.npmjs.com/package/react-native-beacons-manager to implement event check in based on proximity to beacon/location of meeting.

We'll also use GeoFencing option for outdoor events, but inside buildings beacons are the best bet for now, we can acquire a beacon for the chapter with both iBeacon  and Eddystone capabilties or implement it with just software and someone's phone/Bluetooth device will have to play as beacon during events. We'll leave that last part up for discussion after implementation.

**Comment by luisbenan** [comment]
Beacon functionality has been implements, need to integrate with calendar events and test on android

**Comment by abeg777** [comment]
Link check in with user points to automatically update on profile/leaderboard
