### ISSUE TITLE
Build registration form

### ISSUE THREAD

**Issue by luisbenan** [SHPEUCF/shpeucfapp#14]
Build registration form so users can sign up and submit mandatory data

**Comment by luisbenan** [comment]
Built basic form with password validation field, will need to add other important fields for SHPE UCF member information such as undergraduate or graduate? academic year (freshman, sophomore, junior, senior, other), major, etc.

It might be a good idea only to get the most important information on account creation and avoid questions such as "legal status: (U.S. Citizen, Permanent Resident... etc)" as it currently shows on the website, we can allow profile completion later on after the account is created. We'll put this down for discussion.

**Comment by luisbenan** [comment]
Data is now being saved to Firebase. Just need to finish deciding what info will be asked for on user registration

**Comment by HanielDiaz** [comment]
Registration form is now done with all the field that I would be comfortable asking users for.
