### ISSUE TITLE
Email Verification

### ISSUE THREAD

**Issue by HanielDiaz** [SHPEUCF/shpeucfapp#31]
Email verification link does not work on Office 365 which is what knights email uses.

**Comment by luisbenan** [comment]
Interesting. Isn't this just a URL we get from Firebase? 
Is the URL [disabled, not there, or throws error] when viewed from Office365?

It's possible it is being blocked by UCF itself as an untrusted URL. 

Possible solution: Once we setup Firebase to use our shpeucf.com domain for sending emails, all emails come from that domain which might be trusted by UCF firewalls. 

<img width="750" alt="firebaseemails" src="https://user-images.githubusercontent.com/3769480/46387700-f05f3c00-c695-11e8-9f33-9f48d8be2e5a.png">

It can be tricky verifying it, this article that might help:
https://www.macariojames.com/2018/02/19/firebase-custom-domain-verification-namecheap-dns/

**Comment by HanielDiaz** [comment]
I guess this was an issue on Office365's end cause it works now.
