### ISSUE TITLE
Keyboard pushes up screen where textbox is not updated

### ISSUE THREAD

**Issue by SHPETechDirector** [SHPEUCF/shpeucfapp#32]
The only place i've noticed this is in Sign In. We can't see what we're typing when we're typing

**Comment by HanielDiaz** [comment]
The fix for this is to make our own keyboard aware component that works for both android and iOS. Right now we are using RKKeyboard and it's not working the way we want. Once this is removed make sure to permanently remove the RN kitten-ui package and all sub dependencies of it to save on space.

**Comment by HanielDiaz** [comment]
This was fixed in the sign in form but in the create/edit event form and in the registration form it is still happening.

**Comment by HanielDiaz** [comment]
This is now only an issue on iOS. I fixed it in Registration form. RKAvoidKeyboard has become deprecated so we should definitely find a way to replace it.
