### ISSUE TITLE
Bottom Navigation Panel - Initial State 

### ISSUE THREAD

**Issue by esteban737** [SHPEUCF/shpeucfapp#33]
The bottom navigation panel doesn't revert back to initial state. This is undesirable because each of the four primary tabs retains it's previous state even after a different tab has been chosen. This should be modified so that when someone revisits a previously accessed tab, it will have reverted back to its first screen.

**Comment by HanielDiaz** [comment]
This is no longer an issue with the way the app is currently designed. Most reducer calls are done in dashboard and the state is saved in store.
