### ISSUE TITLE
Create Election system

### ISSUE THREAD

**Issue by HanielDiaz** [SHPEUCF/shpeucfapp#39]
Election system must be modular enough where different positions and members can be added and removed by eBoard.
It should record what everyone's vote is(as opposed to being completely anonymous and this is because you need to know to be able to edit your vote if you change your mind)
Must be able to vote, edit vote.

People should apply for a position and then get accepted by the eBoard. This is the easiest way to link people.

- [x]  Allow president to close or open votes during an election

- [ ]  Allow president to transition voted eboard into their respective positions on the app

- [x]  In the event of a tie, allow president to choose the winner of the position

- [x]  Add more alerts to verify actions such voting and setting the order of positions in the back end

- [x]  Take away apply button on election screen once or modify button once someone has applied

- [ ]  Finish handling some of the election stats on the election back-end screen

- [ ]  Ask and reverify if the president wants the election to be closed and finished

**Comment by idelmr** [comment]
Fixed by @esteban737 and restyled by @idelmr last year
