### ISSUE TITLE
Updated the design of the app to make sure everything looks uniform

### ISSUE THREAD

**Issue by HanielDiaz** [SHPEUCF/shpeucfapp#52]
- [x] Create a small design document and upload it to our GitHub wiki
- [x] Make sure that all forms more or less look the same this includes headers and footers
- [x] Use custom components to make your life easier
The app has a lot of different styles on every page. Almost everything looks different.
Learn to make custom components [here](https://medium.com/pvtl/react-native-custom-components-6cd0f6461f67)

**Comment by csepulveda7** [comment]
Most screens have been updated. The dashboard and election screen should be the only ones left to update.
