### ISSUE TITLE
Create a TabBar Component to replace the router's tab Bar

### ISSUE THREAD

**Issue by HanielDiaz** [SHPEUCF/shpeucfapp#60]
Right now the Router has the option of providing a tab bar. This tab bar starts to behave in a weird way when you get deep into stacks. We should create our own tab bar Component to make it easy to implement and keep everything consistent.
- [x] Should allow child components
- [x] Should have a back button that can be disabled

For reference on how to make your own component check out Input.js, Picker.js, and DatePicker.js in Components/General

**Comment by AgentIMR** [comment]
Created and saved under general/NavBar.js
