### ISSUE TITLE
More screen not loading

### ISSUE THREAD

**Issue by grindlock** [SHPEUCF/shpeucfapp#8]
After pulling and merging from the last commit more screen no longer works. I can't find the problem. screenshot below of problem.
![simulator screen shot - iphone 7 plus - 2017-12-15 at 07 22 09](https://user-images.githubusercontent.com/13208203/34042039-ce2b2f44-e168-11e7-9593-8bc51094d19d.png)

**Comment by luisbenan** [comment]
This was due to index.js inside the components folder where ButtonImage is "src/components/general was missing the export * from './ButtonImage'; statement so it could ButtonImage could be used using import { ButtonImage } from './src/components/general';

**Fixed now.**
